In [1]:
import pandas as pd

pd.set_option('display.max_rows', 500)

## Data Preparation

* focus is always to understand the final data
* support each step by visual analytics

## Johns Hopkins GITHUB csv data

In [2]:
data_path = '/home/mitesh/COVID19/EDS_COVID/data/raw/COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv'
pd_raw = pd.read_csv(data_path)
pd_raw.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,7/26/20,7/27/20,7/28/20,7/29/20,7/30/20,7/31/20,8/1/20,8/2/20,8/3/20,8/4/20
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,36157,36263,36368,36471,36542,36675,36710,36710,36747,36782
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,4763,4880,4997,5105,5197,5276,5396,5519,5620,5750
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,27357,27973,28615,29229,29831,30394,30950,31465,31972,32504
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,897,907,907,918,922,925,925,925,937,939
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,932,950,1000,1078,1109,1148,1164,1199,1280,1344

In [3]:
pd_raw.columns[4:]

Index(['1/22/20', '1/23/20', '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       '1/28/20', '1/29/20', '1/30/20', '1/31/20',
       ...
       '7/26/20', '7/27/20', '7/28/20', '7/29/20', '7/30/20', '7/31/20',
       '8/1/20', '8/2/20', '8/3/20', '8/4/20'],
      dtype='object', length=196)

In [10]:
time_index = pd_raw.columns[4:]
df_plot = pd.DataFrame({'data':time_index})
df_plot.head()

      data
0  1/22/20
1  1/23/20
2  1/24/20
3  1/25/20
4  1/26/20

In [11]:
len(pd_raw['Country/Region'].unique())

188

In [12]:
pd_raw['Country/Region']

0                           Afghanistan
1                               Albania
2                               Algeria
3                               Andorra
4                                Angola
5                   Antigua and Barbuda
6                             Argentina
7                               Armenia
8                             Australia
9                             Australia
10                            Australia
11                            Australia
12                            Australia
13                            Australia
14                            Australia
15                            Australia
16                              Austria
17                           Azerbaijan
18                              Bahamas
19                              Bahrain
20                           Bangladesh
21                             Barbados
22                              Belarus
23                              Belgium
24                                Benin
25                               Bhutan
26                              Bolivia
27               Bosnia and Herzegovina
28                               Brazil
29                               Brunei
30                             Bulgaria
31                         Burkina Faso
32                           Cabo Verde
33                             Cambodia
34                             Cameroon
35                               Canada
36                               Canada
37                               Canada
38                               Canada
39                               Canada
40                               Canada
41                               Canada
42                               Canada
43                               Canada
44                               Canada
45                               Canada
46             Central African Republic
47                                 Chad
48                                Chile
49                                China
50                                China
51                                China
52                                China
53                                China
54                                China
55                                China
56                                China
57                                China
58                                China
59                                China
60                                China
61                                China
62                                China
63                                China
64                                China
65                                China
66                                China
67                                China
68                                China
69                                China
70                                China
71                                China
72                                China
73                                China
74                                China
75                                China
76                                China
77                                China
78                                China
79                                China
80                                China
81                                China
82                             Colombia
83                  Congo (Brazzaville)
84                     Congo (Kinshasa)
85                           Costa Rica
86                        Cote d'Ivoire
87                              Croatia
88                     Diamond Princess
89                                 Cuba
90                               Cyprus
91                              Czechia
92                              Denmark
93                              Denmark
94                              Denmark
95                             Djibouti
96                   Dominican Republic
97                              Ecuador
98                                Egypt
99                          El Salvador
100                   Equatorial Guinea
101                             Eritrea
102                             Estonia
103                            Eswatini
104                            Ethiopia
105                                Fiji
106                             Finland
107                              France
108                              France
109                              France
110                              France
111                              France
112                              France
113                              France
114                              France
115                              France
116                              France
117                               Gabon
118                              Gambia
119                             Georgia
120                             Germany
121                               Ghana
122                              Greece
123                           Guatemala
124                              Guinea
125                              Guyana
126                               Haiti
127                            Holy See
128                            Honduras
129                             Hungary
130                             Iceland
131                               India
132                           Indonesia
133                                Iran
134                                Iraq
135                             Ireland
136                              Israel
137                               Italy
138                             Jamaica
139                               Japan
140                              Jordan
141                          Kazakhstan
142                               Kenya
143                        Korea, South
144                              Kuwait
145                          Kyrgyzstan
146                              Latvia
147                             Lebanon
148                             Liberia
149                       Liechtenstein
150                           Lithuania
151                          Luxembourg
152                          Madagascar
153                            Malaysia
154                            Maldives
155                               Malta
156                          Mauritania
157                           Mauritius
158                              Mexico
159                             Moldova
160                              Monaco
161                            Mongolia
162                          Montenegro
163                             Morocco
164                             Namibia
165                               Nepal
166                         Netherlands
167                         Netherlands
168                         Netherlands
169                         Netherlands
170                         New Zealand
171                           Nicaragua
172                               Niger
173                             Nigeria
174                     North Macedonia
175                              Norway
176                                Oman
177                            Pakistan
178                              Panama
179                    Papua New Guinea
180                            Paraguay
181                                Peru
182                         Philippines
183                              Poland
184                            Portugal
185                               Qatar
186                             Romania
187                              Russia
188                              Rwanda
189                         Saint Lucia
190    Saint Vincent and the Grenadines
191                          San Marino
192                        Saudi Arabia
193                             Senegal
194                              Serbia
195                          Seychelles
196                           Singapore
197                            Slovakia
198                            Slovenia
199                             Somalia
200                        South Africa
201                               Spain
202                           Sri Lanka
203                               Sudan
204                            Suriname
205                              Sweden
206                         Switzerland
207                             Taiwan*
208                            Tanzania
209                            Thailand
210                                Togo
211                 Trinidad and Tobago
212                             Tunisia
213                              Turkey
214                              Uganda
215                             Ukraine
216                United Arab Emirates
217                      United Kingdom
218                      United Kingdom
219                      United Kingdom
220                      United Kingdom
221                      United Kingdom
222                      United Kingdom
223                      United Kingdom
224                             Uruguay
225                                  US
226                          Uzbekistan
227                           Venezuela
228                             Vietnam
229                              Zambia
230                            Zimbabwe
231                              Canada
232                            Dominica
233                             Grenada
234                          Mozambique
235                               Syria
236                         Timor-Leste
237                              Belize
238                                Laos
239                               Libya
240                  West Bank and Gaza
241                       Guinea-Bissau
242                                Mali
243               Saint Kitts and Nevis
244                              Canada
245                              Canada
246                              Kosovo
247                               Burma
248                      United Kingdom
249                      United Kingdom
250                      United Kingdom
251                          MS Zaandam
252                            Botswana
253                             Burundi
254                        Sierra Leone
255                         Netherlands
256                              Malawi
257                      United Kingdom
258                              France
259                         South Sudan
260                      Western Sahara
261               Sao Tome and Principe
262                               Yemen
263                             Comoros
264                          Tajikistan
265                             Lesotho
Name: Country/Region, dtype: object

In [13]:
pd[pd_raw['Country/Region'=='US']]

KeyError: False

In [8]:
pd_raw[pd_raw['Country/Region']=='US'].iloc[:,4::].sum(axis=0)

1/22/20          1
1/23/20          1
1/24/20          2
1/25/20          2
1/26/20          5
1/27/20          5
1/28/20          5
1/29/20          5
1/30/20          5
1/31/20          7
2/1/20           8
2/2/20           8
2/3/20          11
2/4/20          11
2/5/20          11
2/6/20          11
2/7/20          11
2/8/20          11
2/9/20          11
2/10/20         11
2/11/20         12
2/12/20         12
2/13/20         13
2/14/20         13
2/15/20         13
2/16/20         13
2/17/20         13
2/18/20         13
2/19/20         13
2/20/20         13
2/21/20         15
2/22/20         15
2/23/20         15
2/24/20         15
2/25/20         15
2/26/20         15
2/27/20         16
2/28/20         16
2/29/20         24
3/1/20          30
3/2/20          53
3/3/20          73
3/4/20         104
3/5/20         174
3/6/20         222
3/7/20         337
3/8/20         451
3/9/20         519
3/10/20        711
3/11/20       1109
3/12/20       1561
3/13/20       2157
3/14/20       2870
3/15/20       2968
3/16/20       4360
3/17/20       6141
3/18/20       8917
3/19/20      14157
3/20/20      19479
3/21/20      25825
3/22/20      33761
3/23/20      43850
3/24/20      54112
3/25/20      66055
3/26/20      84091
3/27/20     102276
3/28/20     122069
3/29/20     141205
3/30/20     162707
3/31/20     188724
4/1/20      214205
4/2/20      244610
4/3/20      276547
4/4/20      309699
4/5/20      337573
4/6/20      367215
4/7/20      397992
4/8/20      429686
4/9/20      464442
4/10/20     497943
4/11/20     527969
4/12/20     556522
4/13/20     581813
4/14/20     608878
4/15/20     637974
4/16/20     669272
4/17/20     701996
4/18/20     730337
4/19/20     756375
4/20/20     783716
4/21/20     809318
4/22/20     837422
4/23/20     871617
4/24/20     907908
4/25/20     940829
4/26/20     968518
4/27/20     990983
4/28/20    1015518
4/29/20    1043038
4/30/20    1072667
5/1/20     1106829
5/2/20     1136024
5/3/20     1161611
5/4/20     1184086
5/5/20     1208271
5/6/20     1233527
5/7/20     1261409
5/8/20     1288587
5/9/20     1314320
5/10/20    1334084
5/11/20    1352962
5/12/20    1375152
5/13/20    1396110
5/14/20    1423727
5/15/20    1449027
5/16/20    1474128
5/17/20    1493132
5/18/20    1514901
5/19/20    1535350
5/20/20    1559157
5/21/20    1584512
5/22/20    1608653
5/23/20    1630476
5/24/20    1651289
5/25/20    1670280
5/26/20    1689163
5/27/20    1707445
5/28/20    1730260
5/29/20    1754764
5/30/20    1779214
5/31/20    1799124
6/1/20     1816479
6/2/20     1837374
6/3/20     1857332
6/4/20     1878683
6/5/20     1903907
6/6/20     1926639
6/7/20     1944370
6/8/20     1961785
6/9/20     1979912
6/10/20    2000706
6/11/20    2023656
6/12/20    2048986
6/13/20    2074542
6/14/20    2094366
6/15/20    2114026
6/16/20    2137731
6/17/20    2163290
6/18/20    2191099
6/19/20    2222579
6/20/20    2255328
6/21/20    2281767
6/22/20    2312303
6/23/20    2347491
6/24/20    2382426
6/25/20    2422299
6/26/20    2467554
6/27/20    2510259
6/28/20    2549864
6/29/20    2590668
6/30/20    2636414
7/1/20     2687588
7/2/20     2742049
7/3/20     2795361
7/4/20     2841241
7/5/20     2891124
7/6/20     2936077
7/7/20     2996098
7/8/20     3054699
7/9/20     3117946
7/10/20    3185737
7/11/20    3245925
7/12/20    3304942
7/13/20    3364157
7/14/20    3431574
7/15/20    3498902
7/16/20    3576157
7/17/20    3647715
7/18/20    3711413
7/19/20    3773260
7/20/20    3834677
7/21/20    3899211
7/22/20    3970121
7/23/20    4038816
7/24/20    4112531
7/25/20    4178970
7/26/20    4233923
7/27/20    4290337
7/28/20    4356206
7/29/20    4426982
7/30/20    4495015
7/31/20    4562107
8/1/20     4620592
8/2/20     4668172
8/3/20     4713540
8/4/20     4771080
dtype: int64